version: '3'
services:
  encar:
    build:
      context: encar/
      dockerfile: 'Dockerfile'

    env_file:
      - 'parser.env'

    environment:
      TZ: 'Asia/Almaty'

    volumes:
      - /home/favorite_motors/favorite_motors/public/share:/share/

  bobaedream:
    build:
      context: bobaedream/
      dockerfile: 'Dockerfile'

    env_file:
      - 'parser.env'

    environment:
      TZ: 'Asia/Almaty'

    volumes:
      - /home/favorite_motors/favorite_motors/public/share:/share/

  kbchachacha:
    build:
      context: kbchachacha/
      dockerfile: 'Dockerfile'

    env_file:
      - 'parser.env'

    environment:
      TZ: 'Asia/Almaty'

    volumes:
      - /home/favorite_motors/favorite_motors/public/share:/share/

networks:
  default:
    external:
      name: traefik
