version: '3.10'
services:
  encar:
    build: ./encar/.
    environment:
      TZ: 'Asia/Almaty'

  bobaedream:
    build: ./bobaedream/.
    environment:
      TZ: 'Asia/Almaty'
  
  kbchachacha:
    build: ./kbchachacha/.
    environment:
      TZ: 'Asia/Almaty'

# networks:
#   default:
#     external:
#       name: traefik